version: '3'

vars:
  glimpse_DB_DSN: '{{.GLIMPSE_DB_DSN | default ""}}'

tasks:
  help:
    desc: print this help message
    cmds:
    - task --list-all
    silent: true

  confirm:
    desc: confirmation prompt
    cmds:
    - |
      echo -n 'Are you sure? [y/N] ' && read ans && [ ${ans:-N} = y ]
    silent: true
    internal: true

  run:
    desc: run the cmd/glimpse application
    cmds:
    - go run ./cmd/glimpse

  migrations:new:
    desc: create a new database migration
    vars:
      NAME: '{{.name | default ""}}'
    cmds:
    - |
      if [ -z "{{.NAME}}" ]; then
        echo "Error: name parameter is required"
        echo "Usage: task migrations:new name=migration_name"
        exit 1
      fi
    - echo 'Creating migration file for {{.NAME}}...'
    - tern new -m ./internal/database/migrations {{.NAME}}

  migrations:up:
    desc: apply all up database migrations
    deps: [ confirm ]
    cmds:
    - echo 'Running up migrations...'
    - tern migrate -m ./internal/database/migrations --conn-string {{.GLIMPSE_DB_DSN}}

  tidy:
    desc: format all .go files, and tidy and vendor module dependencies
    cmds:
    - echo 'Formatting .go files...'
    - go fmt ./...
    - echo 'Tidying module dependencies...'
    - go mod tidy
    - echo 'Verifying dependencies...'
    - go mod verify

# Docker tasks start

  docker:up-dev:
    desc: Start all services
    cmds:
      - echo 'Starting services for dev...'
      - docker compose -f docker-compose.dev.yml up

  docker:down-dev:
    desc: Stop all services
    cmds:
      - echo 'Stopping services for dev...'
      - docker compose -f docker-compose.dev.yml down

  docker:clean-dev:
    desc: Stops all services and cleans volumes
    cmds:
      - echo 'Removing volumes...'
      - docker compose -f docker-compose.dev.yml down -v

  docker:logs-dev:
    desc: View logs
    cmds:
      - docker compose -f docker-compose.dev.yml logs -f

  docker:rebuild-dev:
    desc: Rebuild and start all services
    cmds:
      - echo 'Rebuilding and starting services for dev...'
      - docker compose -f docker-compose.dev.yml up  --build

# Docker tasks end
